export interface SoundLesson {
  id: string;
  symbol: string;
  group: string;
  tip: string;
  words: string[];
  source: string;
  kind: "vowel" | "consonant" | "cluster";
}
// Traditional British teaching chart: 20 vowel entries, 24 consonants, four clusters.
const soundRows = [
  [
    "i-long",
    "iː",
    "长元音",
    "嘴角自然展开，舌头靠前，声音平稳。",
    "sheep green see",
    "Close_front_unrounded_vowel.ogg",
  ],
  [
    "ih",
    "ɪ",
    "短元音",
    "嘴巴放松，短促地发音；和 sheep 的元音对比。",
    "ship fish sit",
    "Near-close_near-front_unrounded_vowel.ogg",
  ],
  [
    "e",
    "e",
    "短元音",
    "嘴张开一点，舌头靠前；这里采用常见教学记号 /e/。",
    "bed red pen",
    "Open-mid_front_unrounded_vowel.ogg",
  ],
  [
    "ae",
    "æ",
    "短元音",
    "嘴张得比 /e/ 大，舌头靠前。",
    "cat map apple",
    "Near-open_front_unrounded_vowel.ogg",
  ],
  [
    "ah",
    "ʌ",
    "短元音",
    "嘴唇放松，不要噘圆，自然发出短音。",
    "sun cup bus",
    "Open-mid_back_unrounded_vowel.ogg",
  ],
  [
    "a-long",
    "ɑː",
    "长元音",
    "嘴张开，舌头靠后，声音平稳。",
    "car star park",
    "Open_back_unrounded_vowel.ogg",
  ],
  [
    "o-short",
    "ɒ",
    "短元音",
    "嘴唇圆一些，嘴张开；这是英式常见元音。",
    "hot dog clock",
    "Open_back_rounded_vowel.ogg",
  ],
  [
    "o-long",
    "ɔː",
    "长元音",
    "嘴唇略圆，舌头靠后。",
    "ball saw talk",
    "Open-mid_back_rounded_vowel.ogg",
  ],
  [
    "uh",
    "ʊ",
    "短元音",
    "嘴唇稍圆，放松地发一个短音。",
    "book good foot",
    "Near-close_near-back_rounded_vowel.ogg",
  ],
  [
    "u-long",
    "uː",
    "长元音",
    "嘴唇向前收圆，保持平稳声音。",
    "moon blue food",
    "Close_back_rounded_vowel.ogg",
  ],
  [
    "er",
    "ɜː",
    "长元音",
    "嘴唇自然放松；这里示范不卷舌的英式元音。",
    "bird girl nurse",
    "Open-mid_central_unrounded_vowel.ogg",
  ],
  [
    "schwa",
    "ə",
    "短元音",
    "很轻、很放松的弱读音，不要用力。",
    "about banana teacher",
    "Mid-central_vowel.ogg",
  ],
  [
    "ei",
    "eɪ",
    "双元音",
    "从 /e/ 自然滑向 /ɪ/。",
    "day rain cake",
    "En-us-day.ogg",
  ],
  [
    "ai",
    "aɪ",
    "双元音",
    "从张口的音滑向 /ɪ/。",
    "my kite light",
    "En-us-eye.ogg",
  ],
  [
    "oi",
    "ɔɪ",
    "双元音",
    "先圆唇，再向 /ɪ/ 滑动。",
    "boy toy coin",
    "En-us-boy.ogg",
  ],
  [
    "ou",
    "əʊ",
    "双元音",
    "从放松的中间音滑向圆唇音。",
    "go boat snow",
    "En-uk-oh.ogg",
  ],
  [
    "au",
    "aʊ",
    "双元音",
    "先张口，再渐渐收圆嘴唇。",
    "cow house mouth",
    "En-us-cow.ogg",
  ],
  [
    "ia",
    "ɪə",
    "双元音",
    "从 /ɪ/ 滑向放松的 /ə/，英式读音。",
    "ear near deer",
    "En-uk-ear.ogg",
  ],
  [
    "ea",
    "eə",
    "双元音",
    "从 /e/ 滑向 /ə/；一些现代英式口音用长元音。",
    "air hair chair",
    "En-uk-air.ogg",
  ],
  [
    "ua",
    "ʊə",
    "双元音",
    "从 /ʊ/ 滑向 /ə/；实际读法随口音而变化。",
    "tour cure pure",
    "En-uk-tour.ogg",
  ],
  [
    "p",
    "p",
    "爆破音",
    "双唇合拢再放开，后面不要加“坡”。",
    "pen pig cap",
    "Voiceless_bilabial_plosive.ogg",
  ],
  [
    "b",
    "b",
    "爆破音",
    "双唇合拢再放开，声带参与振动。",
    "bag bed bus",
    "Voiced_bilabial_plosive.ogg",
  ],
  [
    "t",
    "t",
    "爆破音",
    "舌尖轻碰上齿后方，再迅速放开。",
    "ten top cat",
    "Voiceless_alveolar_plosive.ogg",
  ],
  [
    "d",
    "d",
    "爆破音",
    "位置和 /t/ 相近，声带参与振动。",
    "dog day red",
    "Voiced_alveolar_plosive.ogg",
  ],
  [
    "k",
    "k",
    "爆破音",
    "舌后部抬起再放开，不要读字母 K 的名称。",
    "cat kite book",
    "Voiceless_velar_plosive.ogg",
  ],
  [
    "g",
    "ɡ",
    "爆破音",
    "舌后部抬起再放开，声带参与振动。",
    "go green bag",
    "Voiced_velar_plosive.ogg",
  ],
  [
    "f",
    "f",
    "摩擦音",
    "上齿轻碰下唇，让气流通过。",
    "fish fan leaf",
    "Voiceless_labio-dental_fricative.ogg",
  ],
  [
    "v",
    "v",
    "摩擦音",
    "上齿轻碰下唇，轻轻振动声带。",
    "van vest five",
    "Voiced_labio-dental_fricative.ogg",
  ],
  [
    "th",
    "θ",
    "摩擦音",
    "舌尖轻放在上下齿之间，送气不振动声带。",
    "thin three bath",
    "Voiceless_dental_fricative.ogg",
  ],
  [
    "dh",
    "ð",
    "摩擦音",
    "舌尖位置和 /θ/ 相同，声带参与振动。",
    "this that mother",
    "Voiced_dental_fricative.ogg",
  ],
  [
    "s",
    "s",
    "摩擦音",
    "牙齿靠近，让气流从中间通过。",
    "sun sit rice",
    "Voiceless_alveolar_sibilant.ogg",
  ],
  [
    "z",
    "z",
    "摩擦音",
    "位置和 /s/ 相近，同时振动声带。",
    "zoo zero rose",
    "Voiced_alveolar_sibilant.ogg",
  ],
  [
    "sh",
    "ʃ",
    "摩擦音",
    "嘴唇稍向前，轻轻送气，不加尾音。",
    "ship shop fish",
    "Voiceless_palato-alveolar_sibilant.ogg",
  ],
  [
    "zh",
    "ʒ",
    "摩擦音",
    "位置和 /ʃ/ 相近，声带参与振动。",
    "vision measure treasure",
    "Voiced_palato-alveolar_sibilant.ogg",
  ],
  [
    "h",
    "h",
    "摩擦音",
    "像轻轻呼气，自然接到后面的元音。",
    "hat hand home",
    "Voiceless_glottal_fricative.ogg",
  ],
  [
    "ch",
    "tʃ",
    "破擦音",
    "先短暂挡住气流，再接上 /ʃ/。",
    "chair cheese watch",
    "Voiceless_palato-alveolar_affricate.ogg",
  ],
  [
    "j",
    "dʒ",
    "破擦音",
    "先挡住气流，再发出带声的摩擦音。",
    "jump juice orange",
    "Voiced_palato-alveolar_affricate.ogg",
  ],
  [
    "m",
    "m",
    "鼻音",
    "闭上双唇，声音从鼻腔出来。",
    "map moon room",
    "Bilabial_nasal.ogg",
  ],
  [
    "n",
    "n",
    "鼻音",
    "舌尖碰上齿后方，声音从鼻腔出来。",
    "nose nine sun",
    "Alveolar_nasal.ogg",
  ],
  [
    "ng",
    "ŋ",
    "鼻音",
    "舌后部抬起，声音从鼻腔出来。",
    "sing ring king",
    "Velar_nasal.ogg",
  ],
  [
    "l",
    "l",
    "舌侧音",
    "舌尖碰上齿后方，让气流从舌头两侧通过。",
    "leg leaf yellow",
    "Alveolar_lateral_approximant.ogg",
  ],
  [
    "r",
    "ɹ",
    "近音",
    "舌头不要碰上颚；不是颤舌音。",
    "red rain rabbit",
    "Alveolar_approximant.ogg",
  ],
  [
    "w",
    "w",
    "半元音",
    "先收圆嘴唇，再迅速接后面的元音。",
    "we water window",
    "Voiced_labio-velar_approximant.ogg",
  ],
  [
    "y",
    "j",
    "半元音",
    "舌头靠前抬高，再接后面的元音。",
    "yes yellow young",
    "Palatal_approximant.ogg",
  ],
  [
    "ts",
    "ts",
    "辅音组合",
    "/t/ 紧接 /s/，中间不加元音。",
    "cats hats boats",
    "Voiceless_alveolar_affricate.ogg",
  ],
  [
    "dz",
    "dz",
    "辅音组合",
    "/d/ 紧接 /z/，中间不加元音。",
    "beds hands birds",
    "Voiced_alveolar_affricate.ogg",
  ],
  [
    "tr",
    "tr",
    "辅音组合",
    "/t/ 紧接英语 /r/，两音自然连起来。",
    "tree train try",
    "En-uk-tree.ogg",
  ],
  [
    "dr",
    "dr",
    "辅音组合",
    "/d/ 紧接英语 /r/，两音自然连起来。",
    "draw dress dream",
    "En-us-draw.ogg",
  ],
];
export const sounds: SoundLesson[] = soundRows.map(
  ([id, symbol, group, tip, words, source], i) => ({
    id,
    symbol,
    group,
    tip,
    words: words.split(" "),
    source,
    kind: i < 20 ? "vowel" : i < 44 ? "consonant" : "cluster",
  }),
);

export interface PhonicsLesson {
  id: string;
  pattern: string;
  sound: string;
  group: string;
  words: string[];
  tip: string;
}
const phonicsRows = [
  ["a", "æ", "基础音", "cat map bag"],
  ["e", "e", "基础音", "bed red pen"],
  ["i", "ɪ", "基础音", "sit fish pig"],
  ["o", "ɒ", "基础音", "hot dog pot"],
  ["u", "ʌ", "基础音", "sun cup bus"],
  ...[
    ["b", "b", "bat bed bag"],
    ["c", "k", "cat cup cap"],
    ["d", "d", "dog dad red"],
    ["f", "f", "fan fish fun"],
    ["g", "ɡ", "go gum bag"],
    ["h", "h", "hat hot hen"],
    ["j", "dʒ", "jam jet jump"],
    ["k", "k", "kite king kid"],
    ["l", "l", "leg lip lamp"],
    ["m", "m", "map man milk"],
    ["n", "n", "net nose nine"],
    ["p", "p", "pig pen pet"],
    ["q(u)", "kw", "queen quick quilt"],
    ["r", "ɹ", "red run rain"],
    ["s", "s", "sun sit sock"],
    ["t", "t", "top ten tap"],
    ["v", "v", "van vet vest"],
    ["w", "w", "wet win web"],
    ["x", "ks", "box fox six"],
    ["y", "j", "yes yet yellow"],
    ["z", "z", "zip zoo zero"],
  ].map(([a, b, c]) => [a, b, "基础音", c]),
  ["sh", "ʃ", "辅音字母组合", "ship shop fish"],
  ["ch", "tʃ", "辅音字母组合", "chip chin much"],
  ["th", "θ", "辅音字母组合", "thin thick bath"],
  ["th", "ð", "辅音字母组合", "this that them"],
  ["ph", "f", "辅音字母组合", "phone photo dolphin"],
  ["wh", "w", "辅音字母组合", "what when wheel"],
  ["ck", "k", "辅音字母组合", "duck neck sock"],
  ["ng", "ŋ", "辅音字母组合", "sing ring long"],
  ["nk", "ŋk", "辅音字母组合", "pink bank sink"],
  ["tch", "tʃ", "辅音字母组合", "catch match watch"],
  ["dge", "dʒ", "辅音字母组合", "bridge badge edge"],
  ...[
    ["bl", "black blue block"],
    ["cl", "clap clock class"],
    ["fl", "flag flat flower"],
    ["gl", "glad glass globe"],
    ["pl", "plan plum play"],
    ["sl", "slip slow sleep"],
    ["br", "bring brown bread"],
    ["cr", "crab cry cream"],
    ["dr", "dress drum drop"],
    ["fr", "frog free friend"],
    ["gr", "green grass grow"],
    ["pr", "print press prize"],
    ["tr", "tree train truck"],
    ["sk", "skip skin sky"],
    ["sm", "small smile smell"],
    ["sn", "snow snake snack"],
    ["sp", "spot spin spoon"],
    ["st", "stop star step"],
    ["sw", "swim sweet swing"],
    ["tw", "twin twist twelve"],
    ["scr", "screen scrub scrap"],
    ["spr", "spring spray spread"],
    ["str", "street strong string"],
    ["spl", "splash split splendid"],
    ["squ", "square squid squash"],
  ].map(([a, b]) => [a, "连读", "辅音连缀", b]),
  ["a_e", "eɪ", "不发音 e", "cake name game"],
  ["i_e", "aɪ", "不发音 e", "kite bike five"],
  ["o_e", "əʊ", "不发音 e", "home nose rope"],
  ["u_e", "juː", "不发音 e", "cube cute huge"],
  ["u_e", "uː", "不发音 e", "rule flute June"],
  ["e_e", "iː", "不发音 e", "these theme scene"],
  ["ai", "eɪ", "元音字母组合", "rain mail train"],
  ["ay", "eɪ", "元音字母组合", "day play stay"],
  ["ee", "iː", "元音字母组合", "see tree green"],
  ["ea", "iː", "元音字母组合", "sea leaf read"],
  ["ea", "e", "元音字母组合", "bread head ready"],
  ["ea", "eɪ", "元音字母组合", "great break steak"],
  ["oa", "əʊ", "元音字母组合", "boat coat road"],
  ["ow", "əʊ", "元音字母组合", "snow grow yellow"],
  ["oe", "əʊ", "元音字母组合", "toe goes foe"],
  ["oo", "uː", "元音字母组合", "moon food pool"],
  ["oo", "ʊ", "元音字母组合", "book good foot"],
  ["ue", "uː", "元音字母组合", "blue true clue"],
  ["ew", "uː / juː", "元音字母组合", "new few drew"],
  ["ui", "uː", "元音字母组合", "fruit juice suit"],
  ["ie", "aɪ", "元音字母组合", "pie tie lie"],
  ["ie", "iː", "元音字母组合", "field chief piece"],
  ["ey", "iː", "元音字母组合", "key monkey honey"],
  ["igh", "aɪ", "元音字母组合", "light night high"],
  ["y", "aɪ", "元音字母组合", "my fly sky"],
  ["y", "i", "元音字母组合", "happy baby sunny"],
  ["oi", "ɔɪ", "滑动元音", "coin oil point"],
  ["oy", "ɔɪ", "滑动元音", "boy toy enjoy"],
  ["ou", "aʊ", "滑动元音", "out house cloud"],
  ["ow", "aʊ", "滑动元音", "cow how brown"],
  ["au", "ɔː", "其他元音组合", "autumn sauce August"],
  ["aw", "ɔː", "其他元音组合", "saw draw straw"],
  ["al", "ɔː", "其他元音组合", "walk talk chalk"],
  ["all", "ɔːl", "其他元音组合", "ball tall small"],
  ["ar", "ɑː", "r 相关组合", "car park star"],
  ["or", "ɔː", "r 相关组合", "fork short storm"],
  ["er", "ɜː", "r 相关组合", "her fern term"],
  ["ir", "ɜː", "r 相关组合", "bird girl shirt"],
  ["ur", "ɜː", "r 相关组合", "nurse turn purple"],
  ["air", "eə", "r 相关组合", "air hair chair"],
  ["are", "eə", "r 相关组合", "care share square"],
  ["ear", "ɪə", "r 相关组合", "ear near dear"],
  ["ear", "eə", "r 相关组合", "bear pear wear"],
  ["ear", "ɜː", "r 相关组合", "earth learn heard"],
  ["eer", "ɪə", "r 相关组合", "deer cheer steer"],
  ["ore", "ɔː", "r 相关组合", "more store shore"],
  ["ure", "ʊə / jʊə", "r 相关组合", "cure pure secure"],
  ["kn", "n", "特殊拼写", "knee know knife"],
  ["wr", "ɹ", "特殊拼写", "write wrong wrist"],
  ["mb", "m", "特殊拼写", "lamb comb thumb"],
  ["gn", "n", "特殊拼写", "gnat gnome sign"],
  ["c + e/i/y", "s", "特殊拼写", "city cent cycle"],
  ["g + e/i/y", "常见 dʒ", "特殊拼写", "gem giant gym"],
  ["-le", "əl", "常见词尾", "table apple little"],
  ["-tion", "ʃən", "常见词尾", "station action nation"],
  ["-s", "s", "常见词尾", "cats hats cups"],
  ["-s", "z", "常见词尾", "dogs bags pens"],
  ["-es", "ɪz", "常见词尾", "buses boxes dishes"],
  ["-ed", "t", "常见词尾", "walked jumped washed"],
  ["-ed", "d", "常见词尾", "played cleaned opened"],
  ["-ed", "ɪd", "常见词尾", "wanted needed painted"],
];
export const phonics: PhonicsLesson[] = phonicsRows.map(
  ([pattern, sound, group, words], i) => ({
    id: `phonics-${i}`,
    pattern,
    sound,
    group,
    words: words.toLowerCase().split(" "),
    tip:
      group === "辅音连缀"
        ? "每个辅音仍保留自己的声音，连起来读，中间不加元音。"
        : group === "r 相关组合"
          ? "这里采用英式教学读法；美式英语通常保留 r 的声音。"
          : "观察例词中相同的字母。组合可能还有其他读法，这里练习这一组。",
  }),
);
